version: '3.7'
services:
  dev_store_php:
    container_name: dev_store_php
    build: dev_store_php
    ports:
      - "9000:8000"
    volumes:
      - ./project:/var/www/html

  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: dev_store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

volumes:
  db-data: